name: Run shopify pipeline from shopify_dlt_pipeline.py - Update

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

env:
  DESTINATION__POSTGRES__CREDENTIALS__DATABASE: defaultdb
  DESTINATION__POSTGRES__CREDENTIALS__USERNAME: doadmin
  DESTINATION__POSTGRES__CREDENTIALS__HOST: ecd-data-warehouse-do-user-23910252-0.h.db.ondigitalocean.com
  DESTINATION__POSTGRES__CREDENTIALS__PORT: "25060"
  DESTINATION__POSTGRES__CREDENTIALS__CONNECT_TIMEOUT: "600"
  SOURCES__SHOPIFY_DLT__PRIVATE_APP_PASSWORD: ${{ secrets.SOURCES__SHOPIFY_DLT__PRIVATE_APP_PASSWORD }}
  DESTINATION__POSTGRES__CREDENTIALS__PASSWORD: ${{ secrets.DESTINATION__POSTGRES__CREDENTIALS__PASSWORD }}

jobs:
  maybe_skip:
    runs-on: self-hosted
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: always
          skip_after_successful_duplicate: "false"
          do_not_skip: "[]"

  run_pipeline:
    needs: maybe_skip
    if: needs.maybe_skip.outputs.should_skip != 'true'
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install system build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libssl-dev \
            zlib1g-dev \
            libbz2-dev \
            libreadline-dev \
            libsqlite3-dev \
            wget \
            curl \
            llvm \
            libncursesw5-dev \
            xz-utils \
            tk-dev \
            libxml2-dev \
            libxmlsec1-dev \
            libffi-dev \
            liblzma-dev

      - name: Install Python 3.11 manually with pyenv
        run: |
          curl https://pyenv.run | bash
          export PYENV_ROOT="$HOME/.pyenv"
          export PATH="$PYENV_ROOT/bin:$PATH"
          eval "$(pyenv init -)"
          eval "$(pyenv virtualenv-init -)"
          pyenv install -s 3.11.9
          pyenv global 3.11.9
          python --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_github_action.txt

      - name: Run DLT pipeline
        run: |
          python shopify_dlt_pipeline.py
