name: Shopify to PostgreSQL Sync

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: [self-hosted, do, shopify]  # Matches your runner's labels
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_github_action.txt
          
      - name: Run pipeline
        env:
          DESTINATION__POSTGRES__CREDENTIALS__DATABASE: defaultdb
          DESTINATION__POSTGRES__CREDENTIALS__USERNAME: doadmin
          DESTINATION__POSTGRES__CREDENTIALS__HOST: ecd-data-warehouse-do-user-23910252-0.h.db.ondigitalocean.com
          DESTINATION__POSTGRES__CREDENTIALS__PORT: "25060"
          DESTINATION__POSTGRES__CREDENTIALS__CONNECT_TIMEOUT: "600"
          SOURCES__SHOPIFY_DLT__PRIVATE_APP_PASSWORD: ${{ secrets.SOURCES__SHOPIFY_DLT__PRIVATE_APP_PASSWORD }}
          DESTINATION__POSTGRES__CREDENTIALS__PASSWORD: ${{ secrets.DESTINATION__POSTGRES__CREDENTIALS__PASSWORD }}
        run: python shopify_dlt_pipeline.py